### ISSUE TITLE
build failure with 1.33.0 nightly

### ISSUE THREAD

**Issue by matthiaskrgr** [wdv4758h/cargo-arch#1]
Hi, looks like it is not possible to build with `rustc 1.33.0-nightly (14b96659e 2018-12-25)`

````
   Compiling rustc-serialize v0.3.19
error[E0642]: patterns aren't allowed in methods without bodies
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.3.19/src/serialize.rs:147:45
    |
147 |                                             &f_name: &str,
    |                                             ^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0642`.
````

after running `cargo update` to update deps, build still failed
````
   Compiling cargo-arch v0.1.0 (/tmp/cargo-arch)
error[E0583]: file not found for module `utils`
  --> src/main.rs:15:9
   |
15 | pub mod utils;
   |         ^^^^^
   |
   = help: name the file either utils.rs or utils/mod.rs inside the directory "src"

error: aborting due to previous error

For more information about this error, try `rustc --explain E0583`.
error: Could not compile `cargo-arch`.

To learn more, run the command again with --verbose.
````

**Comment by wdv4758h** [comment]
I think the issue is already fixed. Closing this.
